class PokemonSpecies {
  late int id;
  late String name;
  late int order;
  late int genderRate;
  late int captureRate;
  late int baseHappiness;
  late bool isBaby;
  late bool isLegendary;
  late bool isMythical;
  late int hatchCounter;
  late bool hasGenderDifferences;
  late bool formsSwitchable;
  late dynamic growthRate;
  late List pokedexNumbers;
  late List eggGroups;
  late dynamic color;
  late dynamic shape;
  late dynamic evolvesFromSpecies;
  late dynamic evolutionChain;
  late dynamic habitat;
  late dynamic generation;
  late List names;
  late List palParkEncounters;
  late List flavorTextEntries;
  late List formDescriptions;
  late List genera;
  late List varieties;

  PokemonSpecies(Map<String, dynamic> json) {
    id = json["id"];
    name = json["name"];
    order = json["order"];
    genderRate = json["gender_rate"];
    captureRate = json["capture_rate"];
    baseHappiness = json["base_happiness"];
    isBaby = json["is_baby"];
    isLegendary = json["is_legendary"];
    isMythical = json["is_mythical"];
    hatchCounter = json["hatch_counter"];
    hasGenderDifferences = json["has_gender_differences"];
    formsSwitchable = json["forms_switchable"];
    growthRate = json["growth_rate"];
    pokedexNumbers = json["pokedex_numbers"];
    eggGroups = json["egg_groups"];
    color = json["color"];
    shape = json["shape"];
    evolvesFromSpecies = json["evolves_from_species"];
    evolutionChain = json["evolution_chain"];
    habitat = json["habitat"];
    generation = json["generation"];
    names = json["names"];
    palParkEncounters = json["pal_park_encounters"];
    flavorTextEntries = json["flavor_text_entries"];
    formDescriptions = json["form_descriptions"];
    genera = json["genera"];
    varieties = json["varieties"];
  }
}
